[INFO] [2017-09-11 11:23:04][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 11:23:04][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@71ee2072: startup date [Mon Sep 11 11:23:04 CST 2017]; root of context hierarchy
  [WARN] [2017-09-11 11:23:05][org.mybatis.spring.mapper.ClassPathMapperScanner]No MyBatis mapper was found in '[com.cn.hnust.dao]' package. Please check your configuration.
  [INFO] [2017-09-11 11:23:05][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 11:23:05][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [ERROR] [2017-09-11 11:23:05][org.springframework.test.context.TestContextManager]Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@2d3c117a] to prepare test instance [org.frame.frame.TestMyBatis@429f77c9]
  java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:319)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:212)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:232)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:175)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.core.io.Resource[]' for property 'mapperLocations'; nested exception is java.lang.IllegalArgumentException: Could not resolve resource location pattern [classpath:com/cn/hnust/mapping/*.xml]: class path resource [com/cn/hnust/mapping/] cannot be resolved to URL because it does not exist
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:681)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:121)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	... 25 more
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.core.io.Resource[]' for property 'mapperLocations'; nested exception is java.lang.IllegalArgumentException: Could not resolve resource location pattern [classpath:com/cn/hnust/mapping/*.xml]: class path resource [com/cn/hnust/mapping/] cannot be resolved to URL because it does not exist
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:479)
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:511)
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:505)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1502)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1461)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	... 39 more
Caused by: java.lang.IllegalArgumentException: Could not resolve resource location pattern [classpath:com/cn/hnust/mapping/*.xml]: class path resource [com/cn/hnust/mapping/] cannot be resolved to URL because it does not exist
	at org.springframework.core.io.support.ResourceArrayPropertyEditor.setAsText(ResourceArrayPropertyEditor.java:140)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:430)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:403)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:181)
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:459)
	... 45 more
[INFO] [2017-09-11 11:31:15][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 11:31:15][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@40638da0: startup date [Mon Sep 11 11:31:15 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 11:31:15][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 11:31:15][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [ERROR] [2017-09-11 11:31:16][org.springframework.test.context.TestContextManager]Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@13c29be] to prepare test instance [org.frame.frame.TestMyBatis@14d87994]
  java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:319)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:212)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:232)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:175)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.frame.dao.UserInfoMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.annotation.Resource(shareable=true, mappedName=, description=, name=, type=class java.lang.Object, authenticationType=CONTAINER, lookup=)}
Related cause: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userInfoMapper' defined in file [D:\demo-project\frame\target\classes\org\frame\dao\UserInfoMapper.class]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]: Invocation of init method failed; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [D:\demo-project\frame\target\classes\mappers\UserInfoPOMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'com.csdn.ingo.entity.UserInfoPO'.  Cause: java.lang.ClassNotFoundException: Cannot find class: com.csdn.ingo.entity.UserInfoPO
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:121)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	... 25 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.frame.dao.UserInfoMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.annotation.Resource(shareable=true, mappedName=, description=, name=, type=class java.lang.Object, authenticationType=CONTAINER, lookup=)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:855)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:441)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:419)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:155)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:304)
	... 41 more
[INFO] [2017-09-11 13:46:03][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 13:46:04][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@1cf84e91: startup date [Mon Sep 11 13:46:04 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 13:46:04][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 13:46:04][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [ERROR] [2017-09-11 13:46:04][org.springframework.test.context.TestContextManager]Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@2ed94d6e] to prepare test instance [org.frame.frame.TestMyBatis@3c6a88c9]
  java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:101)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:109)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:75)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:319)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:212)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:232)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:175)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.frame.dao.UserInfoMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.annotation.Resource(shareable=true, mappedName=, description=, name=, type=class java.lang.Object, authenticationType=CONTAINER, lookup=)}
Related cause: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userInfoMapper' defined in file [D:\demo-project\frame\target\classes\org\frame\dao\UserInfoMapper.class]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [spring-mybatis.xml]: Invocation of init method failed; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [D:\demo-project\frame\target\classes\mappers\UserInfoPOMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'com.csdn.ingo.entity.UserInfoPO'.  Cause: java.lang.ClassNotFoundException: Cannot find class: com.csdn.ingo.entity.UserInfoPO
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:121)
	at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:100)
	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:250)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContextInternal(CacheAwareContextLoaderDelegate.java:64)
	at org.springframework.test.context.CacheAwareContextLoaderDelegate.loadContext(CacheAwareContextLoaderDelegate.java:91)
	... 25 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.frame.dao.UserInfoMapper] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@javax.annotation.Resource(shareable=true, mappedName=, description=, name=, type=class java.lang.Object, authenticationType=CONTAINER, lookup=)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:855)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:441)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:419)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:544)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:155)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:304)
	... 41 more
[INFO] [2017-09-11 13:53:19][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 13:53:19][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@1cf84e91: startup date [Mon Sep 11 13:53:19 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 13:53:19][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 13:53:19][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 13:53:20][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@1cf84e91: startup date [Mon Sep 11 13:53:19 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:00:13][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 14:00:13][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@489456cd: startup date [Mon Sep 11 14:00:13 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:00:13][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 14:00:13][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 14:00:13][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@489456cd: startup date [Mon Sep 11 14:00:13 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:18:56][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 14:18:56][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@2ced1f5: startup date [Mon Sep 11 14:18:56 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:18:56][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 14:18:56][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 14:18:56][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@2ced1f5: startup date [Mon Sep 11 14:18:56 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:19:24][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 14:19:24][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@65919c1f: startup date [Mon Sep 11 14:19:24 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:19:24][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 14:19:24][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 14:19:36][org.frame.frame.TestMyBatis]{"age":24,"id":1,"password":"sfasgfaf","userName":"测试"}
  [INFO] [2017-09-11 14:19:36][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@65919c1f: startup date [Mon Sep 11 14:19:24 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:20:33][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 14:20:34][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@489456cd: startup date [Mon Sep 11 14:20:34 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:20:34][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 14:20:34][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 14:20:34][org.frame.frame.TestMyBatis]{"age":24,"id":1,"password":"sfasgfaf","userName":"测试"}
  [INFO] [2017-09-11 14:20:34][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@489456cd: startup date [Mon Sep 11 14:20:34 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:20:41][org.springframework.beans.factory.xml.XmlBeanDefinitionReader]Loading XML bean definitions from class path resource [spring-mybatis.xml]
  [INFO] [2017-09-11 14:20:41][org.springframework.context.support.GenericApplicationContext]Refreshing org.springframework.context.support.GenericApplicationContext@1806c96b: startup date [Mon Sep 11 14:20:41 CST 2017]; root of context hierarchy
  [INFO] [2017-09-11 14:20:41][org.springframework.beans.factory.config.PropertyPlaceholderConfigurer]Loading properties file from class path resource [jdbc.properties]
  [INFO] [2017-09-11 14:20:41][org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor]JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
  [INFO] [2017-09-11 14:20:45][org.frame.frame.TestMyBatis]{"age":24,"id":1,"password":"sfasgfaf","userName":"测试"}
  [INFO] [2017-09-11 14:20:45][org.springframework.context.support.GenericApplicationContext]Closing org.springframework.context.support.GenericApplicationContext@1806c96b: startup date [Mon Sep 11 14:20:41 CST 2017]; root of context hierarchy
  [INFO] [2017-09-25 10:51:15][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:51:15][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:51:15][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:51:15][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:51:17][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:51:17][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:53:52][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:53:52][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:53:53][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:53:53][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:53:53][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:53:53][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:55:42][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:55:42][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:55:43][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:55:43][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 10:55:45][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 10:55:45][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:56:28][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:56:28][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:56:28][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:56:28][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:56:29][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:56:29][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:58:23][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:58:23][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:58:24][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:58:24][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:58:24][org.frame.utils.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:58:24][org.frame.utils.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 11:59:59][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 11:59:59][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 12:00:00][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 12:00:00][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 12:00:00][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 12:00:00][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:42:43][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:42:43][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:42:43][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:42:43][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:42:44][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:42:44][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:44:51][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:44:51][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:44:53][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:44:53][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 14:44:54][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 14:44:54][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 15:01:05][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 15:12:49][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 15:12:49][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:20:06][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:20:06][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:20:07][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:20:07][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:20:07][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:20:07][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:30:04][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:30:04][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:30:05][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:30:05][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:30:06][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:30:06][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:35:48][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:35:48][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:35:49][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:35:49][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-25 17:35:49][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-25 17:35:49][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:24:45][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:24:45][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:24:45][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:24:45][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:24:46][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:24:46][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:36:23][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:36:23][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:36:24][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:36:24][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 10:36:25][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 10:36:25][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:06:11][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:06:11][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:06:12][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:06:12][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:06:13][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:06:13][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:42:57][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:42:57][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:42:58][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:42:58][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:42:59][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:42:59][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:46:11][org.apache.http.impl.execchain.RetryExec]I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://uhome.haier.net:443: The target server failed to respond
  [INFO] [2017-09-26 11:46:11][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome.haier.net:443
  [INFO] [2017-09-26 11:47:17][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:47:17][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:47:18][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:47:18][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-26 11:47:19][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-26 11:47:19][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-28 15:04:00][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-28 15:04:00][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-28 15:04:01][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-28 15:04:01][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-09-28 15:04:02][org.apache.http.impl.execchain.RetryExec]I/O exception (java.net.SocketException) caught when processing request to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-09-28 15:04:02][org.apache.http.impl.execchain.RetryExec]Retrying request to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-11-09 14:27:00][org.frame.utils421.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-11-09 14:27:00][org.frame.utils421.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-11-09 14:27:07][org.frame.utils421.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-11-09 14:27:07][org.frame.utils421.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  [INFO] [2017-11-09 14:27:08][org.frame.utils421.SSLClient]I/O exception (java.net.SocketException) caught when connecting to {s}->https://uhome-gea-us.haieriot.net:443: Connection reset
  [INFO] [2017-11-09 14:27:08][org.frame.utils421.SSLClient]Retrying connect to {s}->https://uhome-gea-us.haieriot.net:443
  